version: '3.7'

services:
  neo4j:
    image: neo4j/neo4j-arm64-experimental:4.3-arm64
    container_name: "supplychain-knowledge-graph"
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/neo"